### ISSUE TITLE
flask not working 

### ISSUE THREAD

**Issue by sourav83** [ufal/viadat#15]
![main py - New folder - Visual Studio Code  Administrator  3_30_2020 10_17_03 PM](https://user-images.githubusercontent.com/62857395/77940543-7afa1900-72d6-11ea-8bd7-da74c0c376a9.png)
when i run python (whatever the folder name).py  its not giving me server for open brownser its only give me new command line
this problem also having in pyler but i already installed pyler and flask give me the solution

**Comment by kosarko** [comment]
This is not a flask help nor a flask issue tracker.
